let showData = [
  {number: "1", title: "Piranesi", author: "Susanna Clarke", year: "2020", status: "new", genre: "Fiction", star:"4.0", comment: "Piranesi is beautiful. The narrator’s descriptor of his world is done with so much care. It’s vivid. There’s love for The House and everything within it. And the author clearly has love for her world too. The mystery of the world unfolds at a wonderful pace and it feels like no moment overstays its welcome."},
  {number: "2", title: "Norwegian Wood", author: "Haruki Murakami", year: "1987", status: "new", genre: "Fiction", star:"4.0", comment: "A deeply sad and pensive coming of age story. An exploration of first love, the complexity of the human condition, and the ever present push and pull of life vs. death. I thought this was a nicely moving story, overall. Murakami’s sex scenes always feel awkwardly detailed to me, but maybe these are my own “taboos” showing rather than a criticism of his work. His writing, internal character monologues, and sense of humor are very nice. There are plenty of moments that we (Laura and I read this together) laughed aloud while reading due to some clever quips between characters—mostly from the over-the-top but lovable Midori. The story has a lot of grey moments full of actions that lead to both positive and negative consequences for the characters. I like this about it. Life’s decisions are almost exclusively grey and I think Murakami captures that through character interactions well here. This is my second Murakami book and I can say that I am officially a fan. I missed some of the more fantastical moments from Kafka on the Shore here. But I did appreciate the familiar sense of dialogue and character internal thought. I thought that Toru (the main character here) was a much more relatable protagonist compared to Kafka. Looking forward to the next one."},
  {number: "3", title: "What I Talk About When I Talk About Running", author: "Haruki Murakami", year: "2007", status: "new", genre: "Fiction", star:"3.5", comment: "In 2022, I had gone to a general doctor for the first time in about 10 years. After moving away from home, I crawled from urgent care to urgent care when I occasionally needed some medicine. But overall, I felt fine so just figured I didn’t need to see anyone. (In retrospect, I very clearly was not taking care of myself.) After seeing an aquantence go through a cancer scare, and being around the same age that I was, I was scared straight. I was 29 and figured that I better start checking in on my body now that I’m getting older. 30 has always stood out to me as an age where, “you know, stuff just starts to not work as well now.” For the most part, my health was okay, but the doctor said that my blood pressure was high. If I couldn’t get it down to a normal level through exercise and a healthier diet, I’d have to start medication soon. So, I started running. I’ve tried a few times in the past and could never keep up the habit, but I didn’t hate it. With this new threat to my life slowly creeping, I was determined to keep it up. So, clearly, this book is about running and I just so happen to be a runner now. I also, just so happened to read my first Murakami novel last year, not knowing he was a long distance runner/novelist. One day, as I ran around my local park, I saw this book propped up against a fence. Literally, on a run, I found this book about running from and author I was just getting acquainted with. It felt like an absolute sign. So, I picked it up."},
  {number: "4", title: "nine different christmases", author: "Tim Rogers", year: "2014", status: "new", genre: "Non-Fiction", star:"5.0", comment: "Okay, I'm not sure how to write about this one. I stumbled upon this essay/bit of writing while surfing the internet for more information about the Youtuber/writer Tim Rogers. I found this website that he posted writing on a decade ago. It's barely formatted HTML but full of writing. Discovering this story felt like reading someone's diary. It felt like an accident. It felt way too personal. I'm still not sure if it's fiction or a retelling of events in his life. Regardless, this 'stumble' really surprised me and left me incredibly moved after reading. It's technically not a book, but it was a weird reading experience that deeply moved me this year and I had to mention it."},
  {number: "5", title: "In An Aeroplane Over The Sea", author: "Kim Cooper", year: "2005", status: "new", genre: "Non-Fiction", star:"3.5", comment: "I love reading music history. In The Aeroplane Over The Sea is an album that I would say that I love, and have easily loved for a long time. However, I don’t know much about the band, Neutral Milk Hotel. Getting a little glimpse into the lives of the individuals around the record was nice. I wish there was even more detail, but I will take this sweet little story for all that it offers."},
  {number: "6", title: "Murakami T: The T-Shirts I Love", author: "Haruki Murakami", year: "2021", status: "new", genre: "Non-Fiction", star:"3.0", comment: "Very cute little book of shirts. Murakami never really gets too deep about any particular topic and I wish that he did a little more. However, I think it’s funny that this book even exists and I think it’s cute. The graphic design and layout are all very pleasing and it’s a joy to flip through and hold. Nothing crazy! You can read it in an hour or two. Easy."},
  {number: "7", title: "The Storyteller: Tales of Life and Music", author: "Dave Grohl", year: "2021", status: "new", genre: "Non-Fiction", star:"4.0", comment: "Bought this as a way to spend an unused audible credit. Now I can say I’m officially a Dave Grohl fan. He seems like a very genuine and positive guy. He’s lived a remarkable life and he tells his stories so lovingly. It’s also full of humor. The man is exactly who he is and is supposed to be. I love the way he talked about his days in Scream. I love hearing his little moments of life’s philosophy and overall his love for music. I feel that love for music too."},
  {number: "8", title: "Before the Coffee Gets Cold", author: "Toshikazu Kawaguchi", year: "2015", status: "new", genre: "Fiction", star:"3.0", comment: "sweet little collection of stories about a coffeehouse with an unusual gift. I found the thought experiment of time traveling to be really great. Each scenario that the participants are involved in were good explorations. However, I disliked most of the buildup for each story. I found the conversation to often be very repetitive, slow, and ultimately the characters weren’t incredibly strong. However, the moments when they go back in time and truly interesting and page turners. I just wish the whole book was so captivating. I like the story about the husband and wife the most. Almost every story deals with the idea of communication and how we shouldn’t hold onto the things we need to say. It’s often those regrets that have us wanting to re-examine our pasts."},
  {number: "9", title: "Anthology of Emo, Vol. 1", author: "Tom Mullen", year: "2020", status: "new", genre: "Non-Fiction", star:"3.0", comment: "I like reading about music history so it’s fun to listen to stories of this wave of Emo. Most of the interviews are with second wave people, who I don’t know a lot about. I bought this book like two years ago around the same time I bought All Ages, the book about the straight edge NYC hardcore scene. It’s cool to see the direct through line from that scene to these bands. The two books go well together. Each time I read an interview from an artist, I listen to at least a few songs from their band. So it took my quite a while to finish this. The star for me was listening to old Jimmy Eat World and The Van Pelt. The Sultans of Sentiment is such an awesome record and I have this book to thank. Overall, many of the interviews are similar. White guys growing up in the 80s listening to punk bands, having minor success, and then being surprised now that people care about their dead bands. Almost all the same. However, it’s still enjoyable and I’m always happy to learn about the history of the scene and get some new bands. I have Vol. 2 of this book. I’ll get to it eventually but will likely take a break for a while."},
  {number: "10", title: "Fahrenheit 451", author: "Ray Bradbury", year: "1953", status: "reread", genre: "Fiction", star:"4.0", comment: "A good read that somehow still feels relevant today. I think Ray Bradbury's writing style is pretty interesting. he uses a lot of run on sentences that really build tension. Jamming words together to describe a chaotic inner turmoil. The story is relatively simple, but it's good. A classic."},
  {number: "11", title: "Catcher in the Rye", author: "J. D. Salinger", year: "1951", status: "reread", genre: "Fiction", star:"5.0", comment: "I love this book. I think the voice of Holden is the reason why you should read it. It’s so vivid. He feels so real. I think it’s one of the most honest portrayals of adolescence in any medium. It’s endearing. It’s sad. It breaks my heart to read his thoughts. I love it."},
  {number: "12", title: "Franny and Zooey", author: "J. D. Salinger", year: "1961", status: "new", genre: "Fiction", star:"3.5", comment: "This book wound up really moving me. I found it a little challenging to get through because it’s essentially just 4 separate conversations happening for a hundred plus pages. The dialog is sometimes a little too ‘old’ for me to fully grasp. But it is expressive. I thought the scenes described were incredibly vivid. I could imagine myself in each one. The religious and intellectual eferences were a bit above me as well. But at its core, the exploration of this dysfunctional family felt real. And I loved that. Anyway, the ending really moved me. The simple notion of taking care of yourself simply because you love something meant a lot to me. The idea that the things you love ARE god. And therefore you should treat those things with respect. I really like that and I wound up thinking about it a lot after reading. So, I liked it. It stayed with me which is the goal of any art form, right?"},
  {number: "13", title: "Nausea", author: "Jean Paul Sartre", year: "1938", status: "new", genre: "Fiction", star:"3.5", comment: "Wow. Finally. I bought this book at Shakespeare and Co. in Paris like 7 years and finished it on the plane home from Europe. What’s strange is that I really enjoy the premise of this book. A man who is so overwhelmed by the normalcy and meaninglessness of every day life driving himself insane? I love it. It’s a great concept. Plus, the writing style is quite beautiful. I think there are a lot of wonderful metaphors and lines in here. The dialog between Any and the narrator was probably my favorite section. It was scalding. Anny’s believe that the main character didn’t change at all after just reading his mental anguish for like 100 pages was a punch to the face. That being said, some of the book and the French references were over my head. Plus, it was hard to read. I think the writing style was just a little too far out of my reach and it became a book that I had to really focus on to read. It kind of reminded me of Tolkien in that way. When I did sit down to read it internally, I really enjoyed it. But very often, I want to read to relax and this book was not that. And that’s why it took me 7 years to finish. But I still liked it and I think I’d like to read it again some day."},
  {number: "14", title: "The Dark Forest", author: "Cixin Liu", year: "2008", status: "new", genre: "Fiction", star:"4.5", comment: "A fantastic, and different sequel to the Three Body Problem. The beginning of the story felt challenging to get into. The new cast of characters, their interweaving plots, with no chapter breaks, took some getting used to. The first quarter of the book I found myself reluctantly moving forward, waiting for it to grab me by the shirt - like Three Body Problem did. And fortunately, it did. And boy, when it did, I couldn’t put it down. Once the new plotlines develop, and the new characters’ paths become more clear, it is fantastic. The key themes of the book are laid out in the first few pages and it takes wandering and compelling character arcs simply to underline the same themes at the end. It’s amazing how deeply I felt as though I understood the principles set before me in the book. It was crushing, hopeful, realistic, and so terribly good. Unfortunately, the slow beginning and re-calibration of the story took some getting used to. I can’t wait to get into the final chapter of these series."},
  {number: "15", title: "Just Kids", author: "Patti Smith", year: "2010", status: "reread", genre: "Non-Fiction", star:"4.0", comment: "After seeing Patti Smith perform at Madison Square Garden, I picked this up and go through the whole thing in a weekend or two. Her early writings of New York are so romantic, full of life, and describe an utterly interesting and bygone era. Also, her love for Robert, so deeply illustrated is a wonder to read. The poetry in her writing. The way her younger self so easily blew through 70s. It’s beautiful. I find as the story goes on, as she meets more and more famous artists of the 70s, the namedropping is lost on me. As their lives get more complex, we lose a little bit of a the beauty of her innocent wonder and instead get into the minutia of the strange characters of the city. I find that less interesting than her simple struggles, and simple love with Robert. It’s a great book to read, particularly while living in New York City and I’m so glad to have returned to it."},
  {number: "16", title: "The Wind-Up Bird Chronicle", author: "Haruki Murakami", year: "1994", status: "new", genre: "Fiction", star:"4.5", comment: "My favorite Murakami so far. Full of deep mystery, surreal wonder, and vivid details. There’s something strange about knowing exactly what Toru ate for breakfast and how he would move the phone receiver from his left to right hand in-between pauses. Little things that make life feel deeply relatable. Just a guy who has been swept up into extraordinary circumstances. And those circumstances and strange encounters tend to be quite gripping. You see, Tori is a vessel for listening. You aren’t hearing one story about a man trying to find his cat, but instead about a dozen different stories, some rooted in real world history and others fully fantastical. Soldiers sneaking across enemy borders, psychics communicating through dreams, rising politicians with unspeakable darkness within them, a young girl slowly taking down her walls. All of these people looped together in strange circumstances and connected to Toru. There are some utterly gripping passages from these tales. Some fall a little bit less flat. And overall, I found the last section of the novel to feel jumbled and less gripping as it switches from being told solely from Toru’s perspective. While it does help with the sense of mystery, it also made be feel a little detached from the story and the events happening. I just wanted to return quickly to the main action because it was so captivating."},
  {number: "17", title: "Akira 1", author: "Katsuhiro Otomo", year: "1984", status: "reread", genre: "Fiction", star:"4.5", comment: "A classic. It's nice to return to it."},
  {number: "18", title: "The Unbearable Lightness of Being", author: "Milan Kundera", year: "1984", status: "reread", genre: "Fiction", star:"4.5", comment: "You know, I went into this one skeptical. I thought I wasn't going to like it as an adult, but I did. I associate this book with a very specific moment in my life and thought it was tied a little bit exclusively to it. There are some passages in here that still resonate a lot with me: the definition portion and the musical references in particular. I like the mix of life philosophy with fiction. I kind of wish I knew of more books that wrote like this style. Give me an ultimatum about life. Give me some story to tie it together. In a way, that's what The Dark Forest did with it's 'Dark Forest' concept."},

];
  
let numberOfItems = showData.length;

console.log(numberOfItems);

// Access the DOM element where you want to display the number
const container = document.getElementById('numberOfItemsContainer');

// Create a new DOM element to display the number
const numberOfItemsElement = document.createElement('span');
numberOfItemsElement.textContent = `${numberOfItems}`;

// Append the new element to the container
container.appendChild(numberOfItemsElement);
