let showData = [
    {number: "1", title: "Distant Worlds", otherActs: "", venue: "Carnegie Hall", comment: "A wonderful way to start off the new year. I was very emotional before they even started. I realized how much of my life I've been playing these games and I knew that some of the songs were going to really move me. The first half they performed various songs from FF 1-6. The tune for FF3 was my favorite—a really cool bouncy little song. The overture and Chocobo theme made me cry. The battle medley was really fun too. The second half was where I wanted to hear the heavy hitters. I was disappointed that the song they played from FF11 was one that I didn’t know. I wanted to hear Ronfaure so badly and that is really my biggest disappointment here. Aerith’s theme was another tear jerker. I enjoyed the tracks from FFX and they even had the original vocalist of the song come out and sing. Pretty cool gesture. The composer of FFXV and Kingdom Hearts was in the audience too. It felt like a really wonderful way to honor the series. I could have sat there for another 2 hours waiting to hear more of my favorite songs across all of the games but they have to draw the line somewhere. I would love to hear more from 10, 7, 11, 8, 14. But it’s all good. I definitely got my money’s worth and I’m so glad I got to experience something like that. "},  
    {number: "2", title: "Knifeplay", otherActs: "w/ Peaer", venue: "Baby's All Right", comment: "Missed most of Peaer’s set but caught some good ones. Knifeplay was sick. Some of their songs are so slow and plodding that it made me really pay attention to how uncomfortable I was in the room. It was scorching hot, my back hurt, and we were jammed in the crowd. Finally, right at the end of the set, fans came on and it was liberating. But it also made the set feel blissful. All of the slow builds paid off. It was a good one. Went with Andrew and Jevins."},  
    {number: "3", title: "Computerwife", otherActs: "", venue: "Elsewhere Zone One", comment: "Quick set to see John. Good Computerwife set. Idk if anything will top the Baby’s performance for me."},  
    {number: "4", title: "Northern Gloom", otherActs: "", venue: "Sleepwalk", comment: "Walked here immediately after seeing Computerwife. We hoofed it and missed the others acts but got there right as Northern Gloom was setting up. Incredibly tight band. Really enjoyed seeing and talking with Cory."},  
    {number: "5", title: "Pon Far", otherActs: "", venue: "Mercury Lounge", comment: "A great group of people. The set was really varied and let Sophie shine. It was really enjoyable. Loved the solo acoustic song as well. Very vulnerable."},
    {number: "6", title: "Hotline TNT", otherActs: "w/ Bazooka, Firewalker", venue: "Tunnel", comment: "Incredible punk show in an abandoned tunnel in Bushwick. Had a blast. Felt like this is why I moved to New York. Reminded me of so many underground shows of my teens and 20s and wow I missed it. I was incredibly excited to see Hotline TNT. MOre to say on this one."},
    {number: "7", title: "Worn", otherActs: "", venue: "Saint Vitus", comment: "Was so interested in more hardcore after the tunnel set that I had to go see more. It was fun."},
    {number: "8", title: "Sinai Vessel", otherActs: "w/ Ben Seretan, Grumpy", venue: "Purgatory", comment: "Fun little show. Seeing Caleb is always a treat and I'm glad to have caught up with him. Grumpy was really impressive. Very funny stage banter. Very sweet little songs. Very cool vocoder vocal effect. Ben Seretan was fantastic as well. I hadn't seen him since seeing a show at his house like four years ago. It was very serene, ambient, and moving. And Sinai Vessel was tight, quiet, intentional. Good show."},
    {number: "9", title: "JPEGMAFIA/Danny Brown", otherActs: "", venue: "Pier 17", comment: "Felt like a damn old man at this one. Stood in the back and felt the pain in my legs at the Pier while the kids went wild up front. But regardless, it was a beautiful day. The Pier is an awesome venue and another that feels so unique to the city. I supposed I wasn't in the mood for a show when I went to this but made it out anyway. Peggy went bananas while Danny calmly walked around stage. There was some banter about being a bald guy that was really fucking funny. All of the STH songs had a full band behind them, which was sick. Fantastic videogame inspired visuals in the background the entire time."},
    {number: "10", title: "Computerwife", otherActs: "w/ Shower Curtain, Downgrade", venue: "Baby's All Right", comment: "I don't think Computerwife will top the first time I saw them. I was so impressed. They were good this gig as well. The openers really impressed me. Shower Curtain are clearly well trained musicians and I'm very excited to hear some of their work in the near future. Downgrade's energy was fun too. Good show."},
    {number: "11", title: "The National", otherActs: "w/ Patti Smith", venue: "Madison Square Garden", comment: "Okay, the big one. This show broke me and built me back up. I feel like I need to write about it in a separate blog post. Highlights: Patti screaming about life. Drinking red wine and sobbing"},
    {number: "12", title: "Alvvays", otherActs: "w/ Alex G, Tanukichan", venue: "Prospect Park", comment: "Another show that was fun because of conveniece. Sat in the grass and listened to some great indie rock. We had a pretty bad view for the first half of the show and I wish it was a little better but it was still fun. Alex G was Alex G. I have no additional thoughts. Alvvays was great. Perhaps too great. They are so spot on that I feel like I'm watching a movie or something. I'm learning that I like some off-the-cuff or weird shit at a live performance. Something that feels like the band might not be able to pull it off. So, they were great. Molly sounded great. I was just a little unmoved. Blue Rev still kicks ass tho."},
    {number: "13", title: "Laveda", otherActs: "w/ Film School", venue: "Mercury Lounge", comment: "Fun show to hang out with Drew and Dave."},
    {number: "14", title: "Spirit of the Beehive", otherActs: "", venue: "Baby's All Right", comment: "Another good last minute show. SOTB is so fucking wacky these days and unfortunately it always has me wishing they were still in their last album cycle. The new songs start and stop so many times that I feel like I can never get into the pocket with their music and my mood. Unfortunate but glad to have seen them."},
    {number: "15", title: "Death Cab for Cutie/The Postal Service", otherActs: "w/ War Paint", venue: "Madison Square Garden", comment: "I kind of can't believe how much I enjoy seated shows at MSG. After being here a few months prior for The National, I was excited to go back to the stadium. Thankfully, John Decker and Jill (and Jill's sisters) had an extra ticket to the show, so I was able to get to go to this. We originally had tickets to see this tour in Connecticut but Laura was sick that weekend. Thankful for the second chance. The show was so much fun. War Paint was a cool, intricate, and interesting opener. Their harmonies were fantastic and some of their song progressions were quite prolonged and meandering, in a very nice way. Death Cab came on and was wonderful. I know what to expect from them at this point and they didn't disappoint. There's a weird thing with Death Cab where I feel like they are almost too good now? I kind of want some slowness and rawness from them. The songs certainly felt like a performance, but what can I really expect from guys singing songs from 20 years ago. They did a good job, I just didn't really feel the proper energy. Instead it was a fun one. The middle of the record, was amazing. Transatlanticism and Passenger Seat had me sitting forward and sobbing down my hands as I held my head. It was wonderful and worth it for the show alone. Those two songs mean a lot to me and I'm very thankful I got to hear them back to back. As for the Postal Service part of the set, it was super fun. I'm less familiar with them but wow, the crowd was excited and the energy was good. Two things stood out: Jenny Lewis was absolutely magestic on stage. She was beautiful in her long white dress. I thought to myself that if I could figure out how to have even an ounce of that beauty, I would be happy in my life. It was like she was Galadriel and I, Gimili. Second, Ben Gibbard on the drums. He killed it and I was really impressed when he got back there, drummed and sang at the same time. It added a bit of change to the performance and this is the type of interesting live thing that I wanted to see from Death Cab, I think. It was impressive. I also really enjoyed my time with John and the Jillbo crew. Enjoyed the conversations with John about music between sets. A good night."},
    {number: "16", title: "Hotline TNT", otherActs: "", venue: "Rainbow Room", comment: "On the 65th floor of Rockefeller Plaza, I looked out the window and thought, 'It's amazing that I live here.' Hotline TNT continues to impress with the weirdest and most varied shows a band has ever played. First the tunnel, now in one of the biggest buildings in NYC. The floor was carpeted. People were handing out glasses of wine with stems. It was bizarre that this even happened and it felt like we didn't belong because it was so swanky. But the show was fun and I'm so thankful for the opportunity. Met Will at the merch table. Bought some records. Hung out with Drew, Dave, Heather, and Laura. It capped off an incredibly busy day for Laura and I and was really quite fun."},
    {number: "17", title: "Tunic", otherActs: "", venue: "Saint Vitus", comment: "Went last minute with Drew. Lots of fun. Tunic was so fast, tight, and brutal. Really enjoyed them."},
    {number: "18", title: "The Menzingers", otherActs: "w/ Microwave, Cloud Nothings", venue: "Knockdown Center", comment: "Fun show. I've seen these guys so many times that it's always a little hard to judge them. They put on a fun show. Played Times Tables and I lost my mind. Some of my favorite songs were from ATP era stuff. All of the oldies and OTIP don't really live up to it anymore because I've seen them performed so many times. Some of the new songs were okay live too. I enjyoed myself."},
    {number: "19", title: "Deafheaven", otherActs: "w/ Touche Amore", venue: "Knockdown Center", comment: "This was a highly anticipated show for me as Sunbather is one of my favorite albums of all time. I've learned that these anniversary shows never quite scratch the itch I'm looking for. They're good and it's nice to hear the songs but nothing will top my memories of hearing them for the first time. There's a little something lost a decade later. That's probably a good thing. Anyway, Touche Amore totally impressed me. They were fantastic and their set was significantly more interesting than when we saw them in Philly last year. I really loved it. Crushing songs. Fun songs. I teared up during Reminders and was happy Laura was by my side. Deafheaven was fantastic as well. I was most impressed by the light show. There were big dramatic swaths of light washing over the band. They must have been some kind of lazer or something because the band would walk forward and backward, in and out of these curtains of light. It was incredible and really contributed to the themes of the album. For the interlude songs, only one or two band members would be on stage and were lit by a singlur light. It was fucking dramatic and amazing. The songs themselves were crushing. George was charasmatic and looming as always with his leather gloves. The band was in full fucking force. I took my earplugs out simply to feel the volume and it was the loudest thing I may have every experienced. Fantastic show. Fantastic band. So happy I was able to see them again, especially with this type of setting."},
  ];
    
  let numberOfItems = showData.length;
  
  console.log(numberOfItems);
  
  // Access the DOM element where you want to display the number
  const container = document.getElementById('numberOfItemsContainer');
  
  // Create a new DOM element to display the number
  const numberOfItemsElement = document.createElement('span');
  numberOfItemsElement.textContent = `${numberOfItems}`;
  
  // Append the new element to the container
  container.appendChild(numberOfItemsElement);
  